### ISSUE TITLE
Need a voluntarily documenter for the simplelogin docs?

### ISSUE THREAD

**Issue by therealmrmuffin** [simple-login/documentation#14]
@nguyenkims I wanted to know if you guys are looking for a voluntarily documenter whom is willing to work on simplelogin's docs?

**Comment by nguyenkims** [comment]
@therealmrmuffin yes, as non-native English speakers we make probably a lot of mistakes so if you spot any error, please create a pull request to fix it.

**Comment by therealmrmuffin** [comment]
@nguyenkims Always happy to help with typos (and vise versa 😉). But do note that i was offering to help make and maintain the docs (and not only fix typos).

**Comment by nguyenkims** [comment]
@therealmrmuffin do you mean having the github permission to merge/review PR? Currently only our team members have this permission on our github actually.

**Comment by therealmrmuffin** [comment]
> @therealmrmuffin do you mean having the github permission to merge/review PR? Currently only our team members have this permission on our github actually.

@nguyenkims not persay, just someone who is a voluntarily documenter part of the SimpleLogin community who wants to help make very, very dilated docs for SimpleLogin (Kind of like how Wikipedia has comunity editors who edit wikipedia on a voluntarily bases).

**Comment by therealmrmuffin** [comment]
Or like how, cpanel in has a documentation team that gets assistants from the community.

**Comment by nguyenkims** [comment]
I see, currently the best way for us to receive contributions is via pull request. It's similar to the contributing method on wikipedia but requires markdown knowledge. It can be nice though as people can edit directly on github and create a merge request after that.

**Comment by therealmrmuffin** [comment]
> I see, currently the best way for us to receive contributions is via pull request. It's similar to the contributing method on wikipedia but requires markdown knowledge. It can be nice though as people can edit directly on github and create a merge request after that.

True, but i am mostly talking about making articles, doc instructions, guides, etc (whatever you want to call it) that don't exists yet. How would you coordinate that with the community?

**Comment by therealmrmuffin** [comment]
I would love to go ham and make like 20 domain name registrar guides for you, if you wish. But the community just needs to know what docs you want help with and stuff.

**Comment by nguyenkims** [comment]
@therealmrmuffin I've updated to readme to include a section on how to add new files :)

**Comment by therealmrmuffin** [comment]
@nguyenkims love it, you bet i'll be busy working on then docs for SL now. :D
