### ISSUE TITLE
I am having this issue while trying to use my own name domain name.

### ISSUE THREAD

**Issue by gkp1** [simple-login/documentation#4]
![image](https://user-images.githubusercontent.com/63517877/145934873-11159d7e-a475-4d74-b14b-a763e46ab7d4.png)

**Comment by nguyenkims** [comment]
That means your domain has been used by a mailbox and this mailbox needs to be changed so you can add the domain into SimpleLogin. Please get in touch with hi@simplelogin.io so we can find a solution.
